### create Project
POST http://localhost:3000/project/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "title":"title of new project",
    "text":"text of new project asfdafasdfsdssf"
}